### ISSUE TITLE
Comparation between analog pin and a variable stored via software

### ISSUE THREAD

**Issue by VittorioEsposito** [leomil72/analogComp#7]
Hi,

Is it possible that the library calls the ISR when a determined voltage on an analog pin is bigger/smaller/equal to a software variable (instead of "a determined voltage on an analog pin is bigger/smaller/equal compared to an other analog pin)?

**Comment by leomil72** [comment]
You could do this by using an analog input pin, reading the voltage and comparing it with a specific value/variable. But I think you would loose time-based response because the AC does this via hardware so it's not software-related and the event raises the interrupt as soon as it is registered by the comparator. Another way is to try to generate an analog signal through a pin and use this signal as a source for an input of the AC, but keep in mind that you should need a chip with an internal DAC or maybe you should try to use an RC filter with a PWM pin.
